USE MySQLDB;
GO
	CREATE PROCEDURE DeleteTuMesaRecords
	AS
		BEGIN TRY
			BEGIN TRAN
				SET NOCOUNT OFF;
				DELETE FROM TuMesa;
			COMMIT TRAN;
		END TRY
		BEGIN CATCH
			IF @@TRANCOUNT > 0
				ROLLBACK TRAN
		END CATCH
	GO

/*EXEC DeleteTuMesaRecords;*/